name: "LiveJournal Crossposting, Reborn!"
id: LJCrosspost
author_link: http://stealthymonkeys.com/
author_name: Stealthy Monkeys Consulting
description: A simple plugin to crosspost entries to LiveJournal (with metadata)
version: 0.0.1
config_settings:
  Server:
    default: http://www.livejournal.com/
tags:
  function:
    LJCrosspostURL: $LJCrosspost::LJCrosspost::Plugin::url
    LJCrosspostLink: $LJCrosspost::LJCrosspost::Plugin::link

